Improve status reporting (#8)
* Add exception handling to lookup plugin

* Update reconcile role to improve status reporting

* Update status when scaling, add readiness probe

* Update the dns names of pods to avoid dns resolution problems.

With just the {HOSTNAME}.${SET_NAME}, the kube-dns was resolving
different ip addresses leading to problems like:
```
2019-03-22 18:31:23.676989 I | pkg/netutil: resolving example-etcd-cluster-5.example-etcd-cluster:2380 to 198.105.244.228:2380
2019-03-22 18:31:23.677718 I | pkg/netutil: resolving example-etcd-cluster-5.example-etcd-cluster:2380 to 172.17.0.12:2380
```

The init script now checks if this pod is scaling, and then check if this pods is joining back. This avoids problems of failures during scaling

diff --git a/roles/reconcile/templates/ss.yaml b/roles/reconcile/templates/ss.yaml
--- a/roles/reconcile/templates/ss.yaml
+++ b/roles/reconcile/templates/ss.yaml
@@ -26,6 +26,17 @@ spec:
       containers:
       - name: "etcd"
         image: "quay.io/coreos/etcd:v3.3"
+        readinessProbe:
+          exec:
+            command:
+              - /bin/sh
+              - -ec
+              - "netstat -tulpn | grep 2379"
+          failureThreshold: 3
+          initialDelaySeconds: 3
+          periodSeconds: 5
+          successThreshold: 1
+          timeoutSeconds: 5
         livenessProbe:
           exec:
             command:
@@ -49,7 +60,7 @@ spec:
         # TODO: set INITIAL_CLUSTER_SIZE my mounting configmap.
         - name: INITIAL_CLUSTER_SIZE
 #          This is a hack, needs to be removed in the future with a version that does not update the value.
-          value: "{{ size }}"
+          value: "{{ initial_size | default(size)}}"
         - name: SET_NAME
           value: "{{ etcd_cluster_name }}"
         volumeMounts:
@@ -63,41 +74,30 @@ spec:
           # store member id into PVC for later member replacement
           collect_member() {
               while ! etcdctl member list &>/dev/null; do sleep 1; done
-              etcdctl member list | grep http://${HOSTNAME}.${SET_NAME}:2380 | cut -d':' -f1 | cut -d'[' -f1 > /var/run/etcd/member_id
+              etcdctl member list | grep http://${HOSTNAME}.${SET_NAME}.{{ etcd_namespace }}.svc.cluster.local:2380 | cut -d':' -f1 | cut -d'[' -f1 > /var/run/etcd/member_id
+              while [ ! -s '/var/run/etcd/member_id' ]; do sleep 1; done
               exit 0
           }
           eps() {
               EPS=""
               for i in $(seq 0 $((${INITIAL_CLUSTER_SIZE} - 1))); do
-                  EPS="${EPS}${EPS:+,}http://${SET_NAME}-${i}.${SET_NAME}:2379"
+                  EPS="${EPS}${EPS:+,}http://${SET_NAME}-${i}.${SET_NAME}.{{ etcd_namespace }}.svc.cluster.local:2379"
               done
               echo ${EPS}
           }
           member_hash() {
-              etcdctl member list | grep http://${HOSTNAME}.${SET_NAME}:2380 | cut -d':' -f1 | cut -d'[' -f1
+              etcdctl member list | grep http://${HOSTNAME}.${SET_NAME}.{{ etcd_namespace }}.svc.cluster.local:2380 | cut -d':' -f1 | cut -d'[' -f1
           }
           # we should wait for other pods to be up before trying to join
           # otherwise we got "no such host" errors when trying to resolve other members
           SET_ID=${HOSTNAME##*[^0-9]}
           for i in $(seq 0 $((${SET_ID}))); do
               while true; do
-                  echo "Waiting for ${SET_NAME}-${i}.${SET_NAME} to come up"
-                  ping -W 1 -c 1 ${SET_NAME}-${i}.${SET_NAME} > /dev/null && break
+                  echo "Waiting for ${SET_NAME}-${i}.${SET_NAME}.{{ etcd_namespace }}.svc.cluster.local to come up"
+                  ping -W 1 -c 1 ${SET_NAME}-${i}.${SET_NAME}.{{ etcd_namespace }}.svc.cluster.local > /dev/null && break
                   sleep 1s
               done
           done
-          # re-joining after failure?
-          if [[ -e /var/run/etcd/member_id ]]; then
-              echo "Re-joining etcd member"
-              member_id=$(cat /var/run/etcd/member_id)
-              # re-join member
-              ETCDCTL_ENDPOINT=$(eps) etcdctl member update ${member_id} http://${HOSTNAME}.${SET_NAME}:2380 | true
-              exec etcd --name ${HOSTNAME} \
-                  --listen-peer-urls http://0.0.0.0:2380 \
-                  --listen-client-urls http://0.0.0.0:2379\
-                  --advertise-client-urls http://${HOSTNAME}.${SET_NAME}:2379 \
-                  --data-dir /var/run/etcd/default.etcd
-          fi
           # etcd-SET_ID
           SET_ID=${HOSTNAME##*[^0-9]}
           # adding a new member to existing cluster (assuming all initial pods are available)
@@ -112,35 +112,55 @@ spec:
                 etcdctl member remove ${MEMBER_HASH}
             fi
             echo "Adding new member"
-            etcdctl member add ${HOSTNAME} http://${HOSTNAME}.${SET_NAME}:2380 | grep "^ETCD_" > /var/run/etcd/new_member_envs
+            etcdctl member add ${HOSTNAME} http://${HOSTNAME}.${SET_NAME}.{{ etcd_namespace }}.svc.cluster.local:2380 | grep "^ETCD_" > /var/run/etcd/new_member_envs
             if [ $? -ne 0 ]; then
                 echo "Exiting"
                 rm -f /var/run/etcd/new_member_envs
                 exit 1
             fi
+            sleep 1
             cat /var/run/etcd/new_member_envs
             source /var/run/etcd/new_member_envs
             collect_member &
             exec etcd --name ${HOSTNAME} \
                 --listen-peer-urls http://0.0.0.0:2380 \
                 --listen-client-urls http://0.0.0.0:2379 \
-                --advertise-client-urls http://${HOSTNAME}.${SET_NAME}:2379 \
+                --advertise-client-urls http://${HOSTNAME}.${SET_NAME}.{{ etcd_namespace }}.svc.cluster.local:2379 \
                 --data-dir /var/run/etcd/default.etcd \
-                --initial-advertise-peer-urls http://${HOSTNAME}.${SET_NAME}:2380 \
+                --initial-advertise-peer-urls http://${HOSTNAME}.${SET_NAME}.{{ etcd_namespace }}.svc.cluster.local:2380 \
                 --initial-cluster ${ETCD_INITIAL_CLUSTER} \
                 --initial-cluster-state ${ETCD_INITIAL_CLUSTER_STATE}
           fi
+          # re-joining after failure?
+           if [[ -e /var/run/etcd/member_id ]]; then
+               echo "Re-joining etcd member"
+               member_id=$(cat /var/run/etcd/member_id)
+               if [ -z "$member_id" ]
+                 then
+                       rm /var/run/etcd/member_id
+                       while [ -e /var/run/etcd/member_id ]; do sleep 1; done
+                       exit 1
+                 fi
+               # re-join member
+               ETCDCTL_ENDPOINT=$(eps) etcdctl member update ${member_id} http://${HOSTNAME}.${SET_NAME}.{{ etcd_namespace }}.svc.cluster.local:2380 | true
+               sleep 1
+               exec etcd --name ${HOSTNAME} \
+                   --listen-peer-urls http://0.0.0.0:2380 \
+                   --listen-client-urls http://0.0.0.0:2379\
+                   --advertise-client-urls http://${HOSTNAME}.${SET_NAME}.{{ etcd_namespace }}.svc.cluster.local:2379 \
+                   --data-dir /var/run/etcd/default.etcd
+           fi
           PEERS=""
           for i in $(seq 0 $((${INITIAL_CLUSTER_SIZE} - 1))); do
-              PEERS="${PEERS}${PEERS:+,}${SET_NAME}-${i}=http://${SET_NAME}-${i}.${SET_NAME}:2380"
+              PEERS="${PEERS}${PEERS:+,}${SET_NAME}-${i}=http://${SET_NAME}-${i}.${SET_NAME}.{{ etcd_namespace }}.svc.cluster.local:2380"
           done
           collect_member &
           # join member
           exec etcd --name ${HOSTNAME} \
-              --initial-advertise-peer-urls http://${HOSTNAME}.${SET_NAME}:2380 \
+              --initial-advertise-peer-urls http://${HOSTNAME}.${SET_NAME}.{{ etcd_namespace }}.svc.cluster.local:2380 \
               --listen-peer-urls http://0.0.0.0:2380 \
               --listen-client-urls http://0.0.0.0:2379 \
-              --advertise-client-urls http://${HOSTNAME}.${SET_NAME}:2379 \
+              --advertise-client-urls http://${HOSTNAME}.${SET_NAME}.{{ etcd_namespace }}.svc.cluster.local:2379 \
               --initial-cluster-token etcd-cluster-1 \
               --initial-cluster ${PEERS} \
               --initial-cluster-state new \
